- apps/client/tailwind.config.js
- apps/server/src/app.module.ts
- apps/server/src/chats/chats.service.spec.ts
- apps/server/src/chats/test-chats.mock.ts
- apps/server/src/questions/questions.service.spec.ts
- apps/server/src/questions/test-questions-service.mock.ts
- apps/server/src/replies/replies.service.spec.ts
- apps/server/src/replies/test-replies-service.mock.ts
- apps/server/src/sessions-auth/sessions-auth.service.spec.ts
- apps/server/src/sessions-auth/test-sessions-auth-service.mock.ts
- apps/server/src/sessions/sessions.service.spec.ts
- apps/server/src/sessions/test-sessions-service.mock.ts
- PR 테스트 액션 실행시에 실패하는 문제가 해당 파일로 보여져, 해당 문제를 수정합니다.
> fix(fe): modify tailwind config file

- apps/client/src/features/session/index.ts
- apps/client/src/features/session/session.util.ts
- apps/client/src/routes/session/$sessionId/$questionId/index.tsx
- apps/client/src/routes/session/$sessionId/index.tsx
- apps/server/src/questions/questions.service.spec.ts
- `beforeload`에서 중복되어 사용되던 코드를 유틸리티 함수로 따로 분리하였습니다.
- close #6
> refactor(fe): add loadSessionData utility for session management

- .github/workflows/deploy.yml
> fix: modify deploy.yml

- apps/client/src/features/session/session.util.ts
클라이언트 빌드에 생기는 오류를 해결했습니다.
- 기존에 작성된 유틸 함수에서 redirect url이 잘못 설정되어 있는 부분을 수정했습니다.
> fix(fe): fix build error

- apps/client/src/components/Header.tsx
- apps/client/src/components/modal/CreateQuestionModal.tsx
- apps/client/src/components/modal/CreateReplyModal.tsx
- apps/client/src/components/modal/SessionParticipantsModal.tsx
- apps/client/src/components/qna/ChattingList.tsx
- apps/client/src/components/qna/QuestionDetail.tsx
- apps/client/src/components/qna/QuestionItem.tsx
- apps/client/src/components/qna/QuestionList.tsx
- apps/client/src/components/qna/ReplyItem.tsx
- apps/client/src/features/auth/auth.hook.ts
- apps/client/src/features/session/session.util.ts
- apps/client/src/features/socket/socket.context.tsx
- apps/client/src/pages/HomePage.tsx
렌더링 성능 최적화를 위해 useShallow 를 이용하는 방식으로 개선했습니다.
- close #23
> refactor(fe): use useShallow access for improved performance

- .github/workflows/deploy.yml
- apps/server/.dockerignore
- apps/server/Dockerfile
- apps/socket-server/.dockerignore
- apps/socket-server/Dockerfile
- 기존 pm2 이용 프로세스가 분리되던 것을 도커로 변경했습니다.
- 다른 인스턴스에 DB를 두고 사용하던 것을 같은 인스턴스로 이전했습니다.
- close #26
- close #27
> feat(be): docker

- apps/server/package.json
- apps/server/src/app.module.ts
- apps/server/src/common/guards/session-token-validation.guard.ts
- apps/server/src/common/redis.module.ts
- apps/server/src/sessions/sessions.service.spec.ts
- apps/server/src/sessions/sessions.service.ts
- pnpm-lock.yaml
- 기존의 유저를 검증하는 가드에서 db에 많은 접근을 하여 부하테스트 시 성능에 문제가 발생하였습니다.
- 이를 해결하기 위해 레디스를 이용한 캐싱을 도입하였습니다.
- close #33
> feat(be): improve guard performance using caching strategy with redis

- apps/server/prisma/migrations/20250122053033_unique_like/migration.sql
- apps/server/prisma/migrations/20250122053355_add_like_index/migration.sql
- apps/server/prisma/migrations/20250122053700_remove_like_index/migration.sql
- apps/server/prisma/schema.prisma
- apps/server/src/questions/questions.repository.ts
- apps/server/src/questions/questions.service.spec.ts
- apps/server/src/questions/questions.service.ts
- 좋아요 기능 토글 로직을 동시성 문제가 발생하지 않도록 개선하였습니다.
- close #38
> fix(be): toggle like

- apps/server/src/auth/auth.controller.ts
- apps/server/src/auth/auth.service.ts
- apps/server/src/common/redis.module.ts
- apps/server/src/main.ts
- 인메모리 리프레시 토큰 저장소를 레디스로 옮겼습니다.
- close #43
> refactor(be): replace in-memory refresh token with redis

- apps/server/src/auth/auth.controller.ts
> fix(be): fix login error

- package.json
프로젝트 전반적으로 성능 개선과 유지보수성, 그리고 확장 가능한 설계를 목표로 Docker 기반 CI/CD, Redis 캐싱, 좋아요 동시성 문제 해결, 프론트엔드 렌더링 버그 수정, 코드 품질 및 프로젝트 구조 개선 등을 중점적으로 진행했습니다.
**[배경]**
- 기존에는 **PM2**를 사용해 애플리케이션을 관리했으나, 컨테이너 기반의 배포 방식으로 전환하여 **일관된 환경**에서 애플리케이션을 실행하고 관리하고자 했습니다.
- Docker 기반으로 CI/CD를 구성하여 개발, 테스트, 배포의 효율성을 높이고자 했습니다.
**[문제]**
- **환경 일관성 부족**
- PM2는 서버 환경에 의존적이며, 배포 과정에서 환경별 차이에 따른 문제가 종종 발생했습니다.
- **복잡한 배포 프로세스**
- 서버 설정과 배포 스크립트의 관리가 점점 복잡해지고, 유지 보수 부담이 증가했습니다.
**[해결]**
- **Docker 컨테이너 기반으로 전환**
- 애플리케이션과 모든 의존성을 컨테이너로 패키징.
- Dockerfile을 작성해서, 개발 및 배포 환경 간의 차이를 제거.
- **CI/CD 파이프라인 개선**
- GitHub Actions를 사용하여 자동화된 빌드, 테스트, 배포 프로세스를 구현.
- PR 머지 시 자동으로 컨테이너 이미지를 빌드하고, 서버에 배포.
**[결과]**
- **일관된 실행 환경**
- 모든 서버에서 동일한 컨테이너 환경을 사용해 실행 오류가 감소.
- **배포 프로세스 간소화**
- GitHub Actions와 Docker를 사용한 CI/CD로, 배포 시간을 단축하고 효율성을 …
> release: 1.0.1

- README.md
- CS 리팩토링 과정에서 변경된 시스템 아키텍처 구조도를 업데이트 합니다.
> docs: update system architecture

- apps/server/src/ai/ai.controller.ts
- apps/server/src/ai/ai.service.ts
- apps/server/src/ai/dto/retry-question.dto.ts
- apps/server/src/ai/swagger/retry-question.swagger.ts
- 질문 개선 API를 만들었습니다.
- close #79
> feat: add question retry API

- apps/server/src/ai/ai.controller.ts
- apps/server/src/ai/ai.service.ts
- apps/server/src/ai/dto/improve-reply.dto.ts
- apps/server/src/ai/dto/retry-question.dto.ts
- apps/server/src/ai/dto/retry-reply.dto.ts
- apps/server/src/ai/swagger/improve-reply.swagger.ts
- apps/server/src/ai/swagger/retry-reply.swagger.ts
- apps/server/src/ai/utils/length-validator.ts
- 응답 개선 API를 만들었습니다.
- 응답 개선 재요청 API를 만들었습니다.
- close #85
> feat(be): add reply improve and retry API

- apps/server/src/ai/dto/create-history.dto.ts
- history type을 정책 변경에 맞게 수정하였습니다.
- 기존의 `SHORTEN_QUESTION`을 제거하고, `IMPROVE_REPLY`을 만들었습니다.
> fix(be): update history prompt type

- apps/client/src/features/ai-history/api/ai-history.ts
- apps/client/src/features/create-update-question/ui/CreateQuestionModalSide.tsx
- apps/client/src/features/create-update-reply/api/improve-reply-retry.api.ts
- apps/client/src/features/create-update-reply/api/improve-reply.api.ts
- apps/client/src/features/create-update-reply/model/useReplyWritingSupport.ts
- apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
- apps/client/src/features/create-update-reply/ui/CreateReplyModalFooter.tsx
- apps/client/src/features/create-update-reply/ui/CreateReplyModalSide.tsx
- apps/client/src/features/create-update-reply/ui/ReplyContentView.tsx
- 닫변 개선 API를 연동하였습니다.
- close #88
> feat(fe): integrate improve reply api

- package.json
> [!Note]
> 
> - AI 기능의 성능을 개선하여 응답을 개선했습니다.
> - 사용자가 보다 원하는 결과가 나올 수 있도록 유도할 수 있는 기능을 추가했습니다.
> - 질문 개선 기능에 이어, 답변 개선 기능을 추가하였습니다.
> - 추가로, 사용자가 악의적인 행동으로 AI 기능을 연속하여 사용하는 것을 방지하는 기능이 추가되었습니다.
> - 마지막으로 질문/답변 축약 기능을 삭제하는 것으로 결정되어 해당 기능을 제거하는 작업이 진행되었습니다.
질문 개선하기 기능의 응답을 개선할 필요가 있었습니다. 또한, 사용자가 악의적인 입력을 하는 것에 대해서 추가적인 대책이 필요했습니다.
프롬프트 엔지니어링만을 이용해서는 눈에 띄게 개선되지 않아, 다른 방법을 추가하기로 결정했습니다.
튜닝을 이용한다면 기존보다 응답이 개선될 것이라고 판단하였고 악의적인 입력에 대해서 완전한 해결을 할 순 없겠지만, 비슷한 입력에 대해서 응답 결과를 데이터로 추가하여 튜닝한다면, 기존보다 악의적인 입력에 대해서 강인해질 수 있다고 판단하였습니다.
튜닝을 위해 데이터셋이 필요해졌고, 이를 위해 데이터셋을 만들었습니다. 학습 데이터를 직접 생성하여 추가하고 이를 GPT를 이용하여 데이터셋을 확장하고, 클로바 스튜디오의 데이터 확장 기능을 이용하여 학습 데이터를 생성했습니다.
> [!IMPORTANT]
> **현재 모델은 인위적으로 생성된 데이터를 통해 학습하였지만, 현재는 사용자의 AI 기능을 사용하고 해당 응답을 채택한 결과를 데이터베이스에 저장하고 있습니다. 이후 모델을 개선할 때 사용할 수 있을 것입니다.**
이후, 모델을 …
> release: 1.2.0

- .github/workflows/deploy.yml
- apps/classifier/.gitignore
- apps/classifier/Dockerfile
- apps/classifier/app.py
- apps/classifier/model.py
- apps/classifier/requirements.txt
- apps/classifier/schemas.py
- 질문과 답변이 개선되었는지 결정하는, 판단하는 classifier 를 추가했습니다.
- BERT 모델을 fine tuning 하였습니다.
- API를 통해서 모델이 판단한 결과를 받아볼 수 있습니다.
- 모델은 인스턴스에 직접 업로드한 상태입니다.
> [!IMPORTANT]
> 실험적인 성격이 강해서, 해당 결과를 너무 신용해서 사용하면 안 됩니다.
> 또한, 답변 개선과 질문 개선의 결과가 나오는 레이블 값이 서로 다릅니다.
> 마지막으로 인스턴스에서 정상적으로 동작하는지 테스트가 필요합니다.
- close #91
> feat(be): add a classifier that determines whether question or reply have been improved

- apps/classifier/app.py
- apps/classifier/model.py
- apps/classifier/schemas.py
- 비속어 감지를 추가했습니다.
- 해당 API로 문장을 보내면, 판별 결과와 점수를 반환합니다.
- close #93
> feat(be): add slang detection

- apps/server/package.json
- apps/server/src/ai/ai.controller.ts
- apps/server/src/ai/ai.service.ts
- apps/server/src/ai/swagger/improve-question.swagger.ts
- apps/server/src/ai/swagger/improve-reply.swagger.ts
- pnpm-lock.yaml
- AI의 응답을 스트리밍 형태로 반환할 수 있도록 하였습니다.
- close #97
> feat(be): stream response

- apps/client/src/entities/session/model/chatting.slice.ts
- apps/client/src/entities/session/model/chatting.type.ts
- apps/client/src/entities/session/ui/ChattingMessage.tsx
- apps/client/src/features/socket/model/socket.service.ts
- apps/client/src/features/socket/model/socket.type.ts
- apps/client/src/shared/ui/popover/Popover.tsx
- apps/client/src/widgets/chatting-list/ChattingList.tsx
- apps/client/tests/QnAPage.spec.ts
- 악성 댓글 필터링 여부를 결정하는 토글 버튼을 추가했습니다.
- 악성 댓글 여부에 따라 텍스트 가시 여부를 결정합니다.
- close #95
> feat(fe): add abuse chatting message filtering feature

- apps/client/src/features/create-update-question/api/improve-question-retry.api.ts
- apps/client/src/features/create-update-question/api/improve-question.api.ts
- apps/client/src/features/create-update-question/model/useQuestionWritingSupport.ts
- apps/client/src/features/create-update-question/ui/AnimatedText.tsx
- apps/client/src/features/create-update-question/ui/CreateQuestionModal.tsx
- apps/client/src/features/create-update-question/ui/CreateQuestionModalFooter.tsx
- apps/client/src/features/create-update-question/ui/QuestionContentView.tsx
- apps/client/src/features/create-update-reply/api/improve-reply-retry.api.ts
- apps/client/src/features/create-update-reply/api/improve-reply.api.ts
- apps/client/src/features/create-update-reply/model/useReplyWritingSupport.ts
- apps/client/src/features/create-update-reply/ui/AnimatedText.tsx
- apps/client/src/features/create-update-reply/ui/CreateReplyModal.tsx
- apps/client/src/features/create-update-reply/ui/ReplyContentView.tsx
- apps/server/src/ai/ai.controller.ts
- AI 기능에 대해서 스트림 형식으로 응답을 받아, 애니메이션 효과를 추가했습니다.
- 백엔드에서 스트림 형식에서 데이터 누락이 생겨서 일부 코드 수정했습니다.
- close #102
> feat(fe): add animated text component for AI features

- apps/client/src/widgets/chatting-list/ChattingList.tsx
- 악성 댓글 토글 버튼의 z-index 값을 조정했습니다.
> fix(fe): adjust z-index of abuse message toggle button

- apps/server/src/ai/guards/restrict-request.guard.ts
- apps/server/src/common/redis.module.ts
- apps/socket-server/prisma/schema.prisma
- 사용자의 ip를 통해 악의적인 요청을 차단하는 기능을 만들었습니다.
- 3초 이내에 같은 ip로부터 ai 기능을 사용하는 요청이 온다면 에러를 반환합니다.
- close #106
> feat(be): restrict request by using token and ip

- apps/server/src/ai/ai.controller.ts
변수를 처리하는 과정에서 오류가 있어서 수정하였습니다.
> fix(be): fix ai controller code

- apps/client/src/entities/session/ui/ChattingMessage.tsx
- 클린봇 멘트를 변경했습니다. `감지한 댓글` -> `감지한 채팅`
> style(fe): update cleanbot alert message
